DROP TABLE USERS cascade constraints;
DROP TABLE PLAN cascade constraints;
DROP TABLE DETAIL_PLAN cascade constraints;
DROP SEQUENCE SEQ_PLAN;
DROP TABLE DETAIL_PLAN;
DROP SEQUENCE SEQ_DETAIL_PLAN;



CREATE TABLE USERS (
  USER_ID     VARCHAR2(30) PRIMARY KEY,
  USER_PW     VARCHAR2(30) NOT NULL,
  USER_NAME    VARCHAR2(30) NOT NULL,
  NICKNAME    VARCHAR2(50) NOT NULL UNIQUE,
  EMAIL       VARCHAR2(50) NOT NULL,
  PHONE       VARCHAR2(20),
  ENROLL_DATE DATE DEFAULT SYSDATE
);

select * from plan;
CREATE TABLE PLAN (
  PLAN_ID           NUMBER PRIMARY KEY,
  WRITER            VARCHAR2(30)
    REFERENCES USERS
      ON DELETE CASCADE,
  TITLE             VARCHAR2(50) NOT NULL,
  START_DATE        DATE DEFAULT SYSDATE,
  END_DATE          DATE DEFAULT SYSDATE,
  CREATE_DATE       DATE DEFAULT SYSDATE,
  REMIND_ALARM_DATE DATE,
  COMPLETE          CHAR(1) DEFAULT 'N' CHECK ( COMPLETE IN ( 'Y', 'N' ) )
);

CREATE SEQUENCE SEQ_PLAN INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

CREATE TABLE DETAIL_PLAN (
  DETAIL_PLAN_ID    NUMBER PRIMARY KEY,
  PLAN_ID           NUMBER
    REFERENCES PLAN
      ON DELETE CASCADE,
  WRITER            VARCHAR2(30)
    REFERENCES USERS
      ON DELETE CASCADE,
  CONTENTS          VARCHAR2(50),
  START_TIME        DATE DEFAULT SYSDATE,
  END_TIME          DATE DEFAULT SYSDATE,
  REMIND_ALARM_TIME DATE DEFAULT SYSDATE,
  CREATE_DATE       DATE DEFAULT SYSDATE,
  COMPLETE          CHAR(1) DEFAULT 'N' CHECK ( COMPLETE IN ( 'Y', 'N' ) )
);

CREATE SEQUENCE SEQ_DETAIL INCREMENT BY 1 START WITH 1 MINVALUE 1 NOCACHE;

INSERT INTO 
USERS(USER_ID, USER_PW, USER_NAME, NICKNAME, EMAIL, PHONE)
VALUES('validUserId0', '123456', 'validUserName0', 'validNickname0', 'valid0@kh.kr','01012345678');
INSERT INTO 
USERS(USER_ID, USER_PW, USER_NAME, NICKNAME, EMAIL, PHONE)
VALUES('validUserId1', '123456', 'validUserName1', 'validNickname1', 'valid1@kh.kr','01012345678');
INSERT INTO 
USERS(USER_ID, USER_PW, USER_NAME, NICKNAME, EMAIL, PHONE)
VALUES('validUserId2', '123456', 'validUserName2', 'validNickname2', 'valid2@kh.kr','01012345678');
INSERT INTO 
USERS(USER_ID, USER_PW, USER_NAME, NICKNAME, EMAIL, PHONE)
VALUES('validUserId3', '123456', 'validUserName3', 'validNickname3', 'valid3@kh.kr','01012345678');
INSERT INTO 
USERS(USER_ID, USER_PW, USER_NAME, NICKNAME, EMAIL, PHONE)
VALUES('validUserId4', '123456', 'validUserName4', 'validNickname4', 'valid4@kh.kr','01012345678');

commit;